apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-notifier-system
  namespace: dsbd-ns
  labels:
    app: alert-notifier-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-notifier-system
  template:
    metadata:
      labels:
        app: alert-notifier-system
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: alert-notifier-system
          image: alert-notifier-system:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: metrics
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS

            - name: SMTP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_SERVER

            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SMTP_PORT

            - name: SENDER_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SENDER_EMAIL

            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_USER

            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SMTP_PASSWORD

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            #limits:
              #memory: "128Mi"
              #cpu: "200m"

# No need to use probes, since the only dependencies are Kafka and application code handles connections itself.
# If kafka dies and code crashes, k8s will restart the pod automatically.
