apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl-secret
  namespace: dsbd-ns
type: Opaque
data:
  nginx-selfsigned.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURuVENDQW9XZ0F3SUJBZ0lVWTNmMXZmMGJmZEg1
    czNXMZRLQ01KZ3lDNVl3RFFZSktvWklWhYTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNTVlF4RGpB
    TUJnT1ZCQWdNQlVsMFlXeHZNUTB3Q3dZRFZRUUhEQVJTYjIxbQpNUTE0REFZRFZRUUtEQVZOZVU5eV
    p6RU1NQW9HQTFVRUN3d0RSR1YyTVJJd0VBWURWUVFEREFsc2IyTmhiR2h2CmMzQwHhcNMjUxMTIyMT
    ExMTQ1WhcNMjYxMTIyMTExMTQ1WjBeMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFSXRhbHkxDTALBgNV
    BAcMBFJvbWUxDjAMBgNVBAoMBU15T3JnMQwwCgYDVQQLDANEZXYxEjAQBgNVBAMMCWxvY2FsaG9zdD
    CCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKbJXbg642K8GADbzPNDQBGDXCSoEPJN5SDe
    cKWwKuPK1ak7zONKJSYYCwyoahzmiSxCri9dk4e7XsEErafMNkZhUCPvWklkNV3t+VvTIFj8t2OK/0
    VX5Ve7PHp+laYjxYGffrm+xXll8mKIyHf5qcgJuFCssB89N570wdxWEOOuFpZ62pBnRg5gOToO2DHJ
    Ans2aylPDnby+0ng0iGv/7g1RMmsmCL9SiUAS/K+H6KVsPHvsgto05CVRx45l8CkE8w4CBV9auuU4Q
    gWe5kn8ovqxiDiDHspEm1Ikr8iKaVJp1xyiGhexZQxl/lpGEfcKLr+BSDZVvY9NqOv0ro9n+ECAwEA
    AaNTMFEwHQYDVR0OBBYEFGbeT/yAK/uhTrViYis6V3ukIjjhMB8GA1UdIwQYMBaAFGbeT/yAK/uhTr
    ViYis6V3ukIjjhMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJ3HOAu/rPBUAvyV
    uIZTrWxO1+lAz25mfCnZNuDWjisBYpGR7dO/d9wjwiJ9Vc6wlXAoNkA/4d66OdfBVoq0mqFyHATjtu
    OMMv0noau+BwCb90KdbmKTh4qPDi8koNN1nNE5KckEgN6NVrlkEOf7v/hjhClxd+Y2ULMi/+IdGZe7
    fPaAfXIqjxoLfLR8XgLvqTS+m3FT04mhUEV0fbbLxp6FXYkGndd+iN463hH89MzcPbfF755r/v5RWi
    pldIa26bfHE+MjOSq5uCtS9DxYaqW1t1u19dOkZdsgA8XqwHG14Sv1ae4UFCS4X6bttoJUO3YbdT8F
    x0UVtY3EdtWNJtI=
  nginx-selfsigned.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQV
    NDQktZd2dnU2lBZ0VBQW9JQkFRQ215VjI0T3VOaXZCZ0EKMjh6elEwQVJnMXdrcVJEeVRlVWczbkNs
    c0Nyanl0V3BPOHpqU2lVbUdBc01xR29jNW9rc1FxNDlYZGt4N3U3QgpCSzJuekRaR1lWQWo3MXBKWk
    RWZDdmbGIweUJZL0xkaml2OUZWK1Z1N3p4NmZwV21JOFdCbjM2NXZzVjVaZkpPCmlNaDNzYW5JQ2Jo
    UXJMQWZQVGVlOU1IY1ZoRGpyaGFXZXRxUVowWU9ZRGk2RHRneHlRSjdObXNwVHc1MjhydEoKNE5J
    aHIvKzROVVRKckpnaS9Vb2xBRXZ5dmgraWxiRHg3N0lMYU5PUWxVY2VOWmZBcEJQTU9BZ1ZmV3Jy
    bE9FSQpGbnVaSi9LTDZzWWc0Z3g3S1JKdFNKSy9JaW1sU2FkY2NpaG9Yc1dVTVpmNWFSaEgzQ2krL2
    dVZzJWYjI5TmFqCnI5SzZQWi9oQWdNQkFBRUNnZ0VBQWpYcDZkQjNyMytCazlWWFNjMlZTVnVUVUND
    ZWVsRWl5ZHZFNXN1ZTJOVWIKSHRCSlNVSy8xTnFYYVI3SUFKS1JDZ2VTbjM5Z2FPekp5OG4wOGxB
    Ky9PZm9NLzlHd0IyMnF3VEdDdncrZkRWUwp6QWdPN3FGRm9zaTgwS3JqUlhMenp1T2dGUFdkcC9N
    bmFPYUVYdVRFNW4vaE5NcFkyNlAvUnBFeVltdGtJRm5CCnQvaXVjZEIyWVJnQmhVZXNjLzFaRFZW
    RGs4aTVLWkp2akNhdFJtMEowM045b2kwM1NsMWdCcDNnY2xLWGIxVkMKdjRkS1AxdFVlWWxPcFov
    NHE3TWVRY3VWY2d3ZXBOSnVJUkwvUVAyVTRsQXQyY2J4UTh5cTY5dy9SbEFmc0JTcgpEV2k1ZDUr
    Z1U5Wm9BMnRQU29CYXhxRXR6d0pxUGVGSk9QN3Eyd2RUb1RLQmdRRGdKa241RUdQVEZKUXFIWGpj
    Ck5rMnY5OHZ2ejJFRjRxSVhhUmlYYUxFWnBVSGZCNUZZWncrbVVWTWZSalcxRHBnTFRnbXJzOHli
    TVVlcUwwMG4KbElVSXM4SWZ3WmtFUmhHL0lnRU1UUmhxdU9yVlhLK1M5QVBwZ0gyUTN6WWhQdzNZ
    U3QyRlMzNGwyUEhKZUFzRApoMXdtTTNiTnd5Y2dnZFRGTEY2RjE0SFo2UUtCZ1FDK2ZHM3ppNXpRen
    RSRFMrVDAzNlFCMmF0dGRmeDNBeVp4CkUxeUoxTTJZZ2Q0a000T3l5a3VSRWg3cGNNQXdXVy9ySWZO
    VExyQ0ZNbWQvVm1XYjlSSVArYXB5NTV2VFJVOXYKaEMxZFFiYlJkQTNFdjNQcnpSWGxtNWdlNG1k
    TkNMaTBoT3g1VTVJSjhuQzhkcTV1MU9kaktYZmpIeENHNFRRWQpWdmE3UmpZak9RS0JnQ1dJZzg1
    KzNoaFVVOU1SaUZGbmptNnUwYWxnVW1ESDZGaC9NcXozzE4vOGVpRThoU3dHClplcDFwN09POENO
    WFJFSndXTkkxazBkUll5eXVLdjg3c1dNWnBxSG1xeGE2SWs1ZEJVdm9CUFNwN2ppNEFuWmIKQWVT
    eHJWVDY2M2Q1dFhuSVgzdVlmcEViMkxEaHR3WnFQaFh2ZkM5TVJGci9Jbis1eEVJcEtnY3hBb0dBV
    0syMzQKeWo3ZXZGN3Rkbjdva2c5alhQRW0yNGlvQmdmVFo2UGRzMVQ4ZWRsTHYzSzBDeElpYUVIc
    XZpYWRjbVRRczVoVQpuUThKWXBqNmtjOTQ4a2YvSnF6R2EwUGp5VkZsRDdkckh4VXV0UWZnT1E0Z0
    8xQjR2TWdBNDYvbkEzZmg5VGhFCmxwOFBSODQwS2FqZXYvNGgwb3dpV2Z2bVI4U2o2Z2ppU0lFQj
    NCRUNnWUFEWlVzeGNiZDFyK0t1dXJQazIrbmgKdVFUT0FmdGdiOG9pUlNldkFjWEw0NkdIbkNEUHl
    pMy9VeHAvMURmVEQvSnFEK0V3TWNUUWtRNlFoRzZKWDdYMkEKaTZVME1PcThIbG5xTHBNYmxIZ0J
    CQzQvN3owR1BoRFl5dmZyQnRWWFQzSE4wYm5MNWxOakg1YWN3aUhmTnpDcAp3VlgwSTYvcnI0aVZ
    xSytubjVUSThBPT0=
